### ISSUE TITLE
New Control : ComboBox

### ISSUE THREAD

**Issue by ohhsodead** [RobinPerris/DarkUI#12]
Hello, friend

Are there any ideas for adding or other implementations of workarounds for a control?

Thanks you.

**Comment by RobinPerris** [comment]
I do remember looking in to implementing a ComboBox originally, however I never had an actual use case for it.

If you look through the .NET reference source you can see how the default WinForms control operates:
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ComboBox.cs,e83c7b91eda8635a

You could implement similar functionality by glueing together a `DarkTextBox` and `DarkListView`.

Another option I used quite extensively is taking open-source implementations of controls and modifying the drawing code to use the `DarkUI` colours instead.

Having a quick search around I found this, which may offer a shortcut:
https://www.codeproject.com/Articles/30958/How-to-create-a-custom-ComboBox-from-scratch

In terms of developing an official DarkUI ComboBox control, I'm afraid I'm no longer actively working on extending the library out as I now work exclusively on cross-platform UI frameworks.

I'm happy to take a pull-request if you end up developing this though!

Good luck. Feel free to re-open the issue if you need any more help with this.

**Comment by RobinPerris** [comment]
@ohhsodead I have a pull request that adds a `DarkComboBox` here: https://github.com/RobinPerris/DarkUI/pull/19 I realise this is very late, but if you're still using the library can you check if that's what you need?

**Comment by ohhsodead** [comment]
Hello! Nice to see you're working on this project again! I will wait until actual source is updated then will update my copy too.
