### ISSUE TITLE
DarkSectionPanel Anchor Doesn't Work Properly?

### ISSUE THREAD

**Issue by ohhsodead** [RobinPerris/DarkUI#14]
After using the designer to set controls (like **DarkSectionPanel**) anchor properties that are mostly at the edge of my **DarkForm**, such as doing **Left, Top, Bottom** so it's stuck to the left side of the form. Running the app in the normal window state and then maximising doesn't keep the anchoring so that they're stretched across the side of the forms. If you would like to me to include some screenshots to show what I mean. Thanks.

**Comment by RobinPerris** [comment]
Sorry, I'm not entirely sure what you're asking. As you've closed the issue, I'm assuming you've managed to fix it?

**Comment by ohhsodead** [comment]
That's my bad I was having a moment. I forgot there was a container for my controls forgot to  and set it's anchor properties.
