### ISSUE TITLE
Scrollbar of DarkListView doesn't work properly 

### ISSUE THREAD

**Issue by Sgridev** [RobinPerris/DarkUI#17]
Hi, scrollbar of DarkListView in the nuget version of DarkUI doesn't work properly.
It works properly if instead i reference the DarkUI project coming from Github (which doesn't have the DarkComboBox, why?)

**Comment by RobinPerris** [comment]
Similar to https://github.com/RobinPerris/DarkUI/issues/15

It looks like someone has forked the DarkUI project, made some modifications, and published to NuGet. I have no control over the package, nor any of the modifications made to it.

You'll need to get in touch with the publisher if you have issues specific to their version.

**Comment by RobinPerris** [comment]
Quick update: I got in touch and it turns out the NuGet version is published for use in a game development engine called Orion. However, it is unsupported and has known bugs.

You can check out the code here if you need it: https://github.com/AscensionGameDev/DarkUI

**Comment by Sgridev** [comment]
Thank you very much for the update.

**Comment by ParchmentWolf** [comment]
I kill it with fire D: <

**Comment by Sgridev** [comment]
Fixed it.
Downloaded @SpiceyWolf repo, added project to solution, removed new DarkListView control from the project, added @RobinPerris DarkListView control to the project and it worked.

**Comment by ParchmentWolf** [comment]
I posted the nuget I did not make the fork.

Edit: the nuget is now dead as well

**Comment by Sgridev** [comment]
Why did you decide to remove it?
I know that it's unsupported but I found it very useful since there is no much alternatives on nuget.

**Comment by ParchmentWolf** [comment]
I haven't coded in .net for a long time and have no intentions of doing so again so there will be 0 maintenance from me, I've offered for Robin to take the package is if he wants to officially host it, or if the Ascension devs want to host a different id and maintain theirs they can.

**Comment by Sgridev** [comment]
I guess it's reasonable by your side.
Hope someone will host it officially.

**Comment by RobinPerris** [comment]
@Sgridev It seems a shame to take down something people were using. I'll talk to the original author of the modifications and see if I can get them merged in to this repo.

From there, I'll see if I can get things published to NuGet for people to use.

@SpiceyWolf Thanks for the help and the quick response :+1:
