### ISSUE TITLE
Dark ComboBox missing

### ISSUE THREAD

**Issue by DAVIDSystems** [RobinPerris/DarkUI#18]
Thanks for the cool library, but i'm really mssing a dark DropDown ComboBox.
Any chance to add this ?

**Comment by ohhsodead** [comment]
@DAVIDSystems Duplicate of issue #15 - You should use a fork of this project, it will have extended controls support including the combobox.

**Comment by RobinPerris** [comment]
@DAVIDSystems I have a pull request to add this. Can you check out https://github.com/RobinPerris/DarkUI/pull/19 and see if that's what you need?
