### ISSUE TITLE
The specified key did not exist in the directory

### ISSUE THREAD

**Issue by DragonicK** [RobinPerris/DarkUI#2]
Hello, Robin. I have a problem when im trying to add some content on darkdockpanel.

 darkDockPanel1.AddContent(new DarkDockContent());

The specified key did not exist in the directory.

**Comment by RobinPerris** [comment]
`DarkDockContent` has to have either the `DockArea` or the `DefaultDockArea` property set.

Not really sure what the use-case is for creating content without any... well, content. Generally I create a custom user control that inherits from `DarkDockContent`.

In any case, you can do it by setting the `DefaultDockArea` in the initialisation of the object. In your case, it would look like this (change the dock area to whatever you want it to be):

```csharp
darkDockPanel1.AddContent(new DarkDockContent { DefaultDockArea = DarkDockArea.Document });
```

**Comment by DragonicK** [comment]
Thanks, it is working.
