### ISSUE TITLE
DarkTextBox => White Scrollbar

### ISSUE THREAD

**Issue by DAVIDSystems** [RobinPerris/DarkUI#22]
Again, thanks for this great library.
Maybe i missed something, but how can i get the scrollbar in a multiline DarkTextBox displayed in dark mode ?

Thanks,

Michael

**Comment by RobinPerris** [comment]
It's one of the limitations of the library unfortunetly. The default WinForms `TextBox` control is just a wrapper and doesn't have much customisation I can hook in to.

One potential workaround is to create a new control which inherits from the `ScrollViewBase` and move an auto-sized textbox around to mimic the effect of scrolling. I have no idea how viable this is, however.
