### ISSUE TITLE
Allowing DarkDocument Tab to be dragged out.

### ISSUE THREAD

**Issue by EthemAcar-Dev** [RobinPerris/DarkUI#29]
Hi,

I would like to know how i can allow DarkDocument tab to be dragged out to a new window and also to be dragged in as a tab back again.

Thank you.

**Comment by RobinPerris** [comment]
This is not possible with the current implementation. DarkUI was designed to be very lightweight and uses custom user controls for simulating document windows.

If you want a more feature-rich docking system, I'd recommend using something like [DockPanelSuite](https://github.com/dockpanelsuite/dockpanelsuite)
