### ISSUE TITLE
DarkComboBox Not Drawing Correctly

### ISSUE THREAD

**Issue by Kyle-Lancaster** [RobinPerris/DarkUI#35]
The DarkComboBox is not drawing correctly if it is in a TableLayoutPanel cell and "Dock" is set to "Fill" and the form is resized. It seems to only draw correctly for the region that represents the original size of the DarkComboBox.

As a work around, when the DarkComboBox is created I set the width to something larger than the form will ever be (such as int.MaxValue) this draws the DarkComboBox correctly even when the form is shrunk. Example workaround code (where "comboControl" is the DarkComboBox):

`comboControl.Size = new Size(int.MaxValue, comboControl.Size.Height);`

Here is a screenshot of the DarkComboBox before the form is resized:

![image](https://user-images.githubusercontent.com/51718748/89707524-285cf780-d96f-11ea-922d-a0578e6e7100.png)

And here it is after the form is resized:

![image](https://user-images.githubusercontent.com/51718748/89707529-31e65f80-d96f-11ea-81a5-dc713cc1014f.png)

**Comment by RobinPerris** [comment]
Can you confirm which version you're using? This should have been fixed by https://github.com/RobinPerris/DarkUI/pull/26 (version 2.0.1)

**Comment by Kyle-Lancaster** [comment]
According to the NuGet Package Manager I am using 2.0.1, but if I check the reference properties or file properties of the DLL then it is 2.0.0

Not sure what is going on. I installed it via the NuGet Package Manager.

![image](https://user-images.githubusercontent.com/51718748/89710397-e178fd00-d982-11ea-9ee6-40853c799c69.png)

![image](https://user-images.githubusercontent.com/51718748/89710419-2bfa7980-d983-11ea-9871-9e798d8f5b33.png)

![image](https://user-images.githubusercontent.com/51718748/89710431-446a9400-d983-11ea-9391-3206cf4a255b.png)

**Comment by Kyle-Lancaster** [comment]
Moments after I previously commented I saw you just released 2.02 on NuGet. After installing that version the issue is resolved.

Thanks a lot!

**Comment by RobinPerris** [comment]
Yeah, I was able to replicate your issue by swapping to NuGet 2.0.1. Looks like I botched the release and included an outdated DLL.

Sorry about that. 2.0.2 also includes another fix for dropdown items not clearing as an added bonus. 👍
