### ISSUE TITLE
No scroll event

### ISSUE THREAD

**Issue by Alex4SSB** [RobinPerris/DarkUI#37]
Haven't checked all controls, but the DarkScrollBar and DarkListView don't seem to have OnScroll events.

Do you plan on adding these? Anyway, I added it in a local copy for my app.

**Comment by RobinPerris** [comment]
Use `ValueChanged` on `DarkScrollBar`.

As far as I know, a standard WinForms `ListView` control doesn't expose an `OnScroll` event - neither does the DarkUI variant.

**Comment by Alex4SSB** [comment]
Ok, thanks for the tip.
