### ISSUE TITLE
How Can I Get Panel + Darkscrollbar

### ISSUE THREAD

**Issue by ghost** [RobinPerris/DarkUI#70]
Is their  anyway i can use darkscrollbar with a panel or sectionpanel ?

**Comment by JohnLamontagne** [comment]
@ShubhamSus Unfortunately Robin Perris, the creator and maintainer of this repository, passed away a few years ago. I do not believe there is anyone else with the ability to manage this repository. 

Just letting you know as the support on this going forward will likely be zero.

**Comment by aeirex** [comment]
Robin passed away.
