### ISSUE TITLE
Where can I get the Icons Used?

### ISSUE THREAD

**Issue by vsnthdev** [RobinPerris/DarkUI#8]
How to restore a saved layout?

**Comment by vsnthdev** [comment]
Hello, I am a fan of DarkUI, as I am using it to create an IDE to edit Electron Framework applications. At first, I could not see how to retain/restore the layout of the panel. So, I raised this Issue. But then I checked the C# Example project code and got the code for it. Now my current issue is the icons, I can't get the icons that I needed. Can you please tell me where or how did you get the icons used in the C# Example project?

**Comment by RobinPerris** [comment]
You can get them as part of the [Visual Studio Image Library](https://www.microsoft.com/en-gb/download/details.aspx?id=35825).

**Comment by vsnthdev** [comment]
Thanks for replying so quickly. You really have done a great job of creating the library. I have downloaded the Images. As the library is excellent and there is no problem now. Let's close the issue here.

**Comment by RobinPerris** [comment]
Please open a new issue for new problems - changing the title on an existing conversation is confusing for anyone who comes across this with the same question.
